--10
SELECT COUNT(*) AS QuantidadeUsuario FROM(
SELECT USUARIO.NOME AS NOME, COUNT(REACAO.CODIGO) AS NUMEROREACOES FROM POST 
JOIN REACAO ON POST.CODIGO= REACAO.COD_POST
JOIN USUARIO ON POST.EMAIL_USUARIO=USUARIO.EMAIL
WHERE (REACAO.DATAREACAO BETWEEN REACAO.DATAREACAO
    AND DATE(POST.DATAPOST, '+1 day','-1 minute', 'localtime'))
    AND (POST.DATAPOST BETWEEN DATE('now', '-365 days', 'localtime')
    AND DATE('NOW'))
    AND POST.PAIS ='Brasil'
    GROUP BY POST
    HAVING NUMEROREACOES > 0
);

--11
SELECT 
		case when CAST((JULIANDAY('NOW', 'LOCALTIME') - JULIANDAY(USUARIO.NASCIMENTO, 'LOCALTIME'))/365.2422 AS INTEGER)  < 18 then  
        '-18'  
        when CAST((JULIANDAY('NOW', 'LOCALTIME') - JULIANDAY(USUARIO.NASCIMENTO, 'LOCALTIME'))/365.2422 AS INTEGER)   between 18 and 21 then  
        '18-21'  
        when  CAST((JULIANDAY('NOW', 'LOCALTIME') - JULIANDAY(USUARIO.NASCIMENTO, 'LOCALTIME'))/365.2422 AS INTEGER)   between 21 and 25 then  
        '21-25'
		when  CAST((JULIANDAY('NOW', 'LOCALTIME') - JULIANDAY(USUARIO.NASCIMENTO, 'LOCALTIME'))/365.2422 AS INTEGER)   between 25 and 30 then  
        '25-30'
		when  CAST((JULIANDAY('NOW', 'LOCALTIME') - JULIANDAY(USUARIO.NASCIMENTO, 'LOCALTIME'))/365.2422 AS INTEGER)   between 30 and 36 then  
        '30-36'
		when  CAST((JULIANDAY('NOW', 'LOCALTIME') - JULIANDAY(USUARIO.NASCIMENTO, 'LOCALTIME'))/365.2422 AS INTEGER)   between 36 and 43 then  
        '36-43'
		when  CAST((JULIANDAY('NOW', 'LOCALTIME') - JULIANDAY(USUARIO.NASCIMENTO, 'LOCALTIME'))/365.2422 AS INTEGER)   between 43 and 51 then  
        '43-51'
		when  CAST((JULIANDAY('NOW', 'LOCALTIME') - JULIANDAY(USUARIO.NASCIMENTO, 'LOCALTIME'))/365.2422 AS INTEGER)   between 51 and 60 then  
        '51-60'
		else '60+'
        end as FAIXAETARIA,
COUNT(REACAO.CODIGO) AS QUANTIDADE FROM POST
JOIN REACAO ON POST.CODIGO= REACAO.COD_POST
JOIN COMPARTILHAMENTO ON POST.CODIGO = COMPARTILHAMENTO.COD_POST
JOIN CITACAO ON POST.CODIGO = CITACAO.COD_POST
JOIN USUARIO ON REACAO.EMAIL_USUARIO=USUARIO.EMAIL
WHERE CODIGOGRUPO = $_POST['grupo']
AND REACAO.DATAREACAO BETWEEN date ('now', '-."$_POST['grupo']"."days"', 'localtime' ) 
AND DATE ('now', 'localtime')
GROUP BY FAIXAETARIA
ORDER BY QUANTIDADE DESC
LIMIT 1;

--12
SELECT ASSUNTO, COUNT(ASSUNTO) AS INTERACOES FROM POST 
JOIN ASSUNTOPOST ON POST.CODIGO= ASSUNTOPOST.CODIGOPOST
JOIN ASSUNTO ON ASSUNTO.CODIGO= ASSUNTOPOST.CODIGOASSUNTO
JOIN(
SELECT COUNT(*) AS REACAO FROM REACAO
GROUP BY COD_POST
)
JOIN(
SELECT COUNT(*) AS COMPARTILHAMENTO FROM COMPARTILHAMENTO
GROUP BY COD_POST)
GROUP BY ASSUNTO
ORDER BY INTERACOES DESC;


--13



--14

SELECT u1.NOME AS USUARIOA, GROUP_CONCAT(u2.NOME) AS USUARIOB
FROM USUARIO u1,USUARIO u2
JOIN (SELECT POST.EMAIL_USUARIO, ASSUNTO.CODIGO FROM ASSUNTO
    JOIN ASSUNTOPOST ON ASSUNTOPOST.CODIGOASSUNTO = ASSUNTO.CODIGO
    JOIN POST ON ASSUNTOPOST.CODIGOPOST = POST.CODIGO
WHERE DATE(POST.DATAPOST, 'localtime') BETWEEN DATE ('now', '-12 months', 'localtime') 
AND DATE ('now', 'localtime')    
GROUP BY POST.EMAIL_USUARIO,ASSUNTO.CODIGO
ORDER BY COUNT(ASSUNTO) DESC
LIMIT 10) ASSUNTOSPOSTUSUARIO1 ON ASSUNTOSPOSTUSUARIO1.EMAIL_USUARIO=U1.EMAIL
JOIN (SELECT POST.EMAIL_USUARIO, ASSUNTO.CODIGO,  ASSUNTO.ASSUNTO FROM ASSUNTO
    JOIN ASSUNTOPOST ON ASSUNTOPOST.CODIGOASSUNTO = ASSUNTO.CODIGO
    JOIN POST ON ASSUNTOPOST.CODIGOPOST = POST.CODIGO
WHERE DATE(POST.DATAPOST, 'localtime') BETWEEN DATE ('now', '-12 months', 'localtime') 
AND DATE ('now', 'localtime')    
GROUP BY POST.EMAIL_USUARIO,ASSUNTO.CODIGO
ORDER BY COUNT(ASSUNTO) DESC
LIMIT 10) ASSUNTOSPOSTUSUARIO2 ON ASSUNTOSPOSTUSUARIO2.EMAIL_USUARIO=U2.EMAIL
AND ASSUNTOSPOSTUSUARIO1.CODIGO =ASSUNTOSPOSTUSUARIO2.CODIGO
WHERE NOT EXISTS(SELECT 1
                 FROM AMIZADE 
                 WHERE (AMIZADE.EMAIL_USUARIO1 = u1.EMAIL AND
                        AMIZADE.EMAIL_USUARIO2 = u2.EMAIL)
                     OR(AMIZADE.EMAIL_USUARIO1 = u2.EMAIL AND
                        AMIZADE.EMAIL_USUARIO2 = u1.EMAIL))
AND u1.EMAIL != u2.EMAIL
GROUP BY u1.EMAIL
HAVING COUNT(*) >= 1;


--15
UPDATE USUARIO 
SET ATIVO = 0 
FROM (SELECT CASE WHEN MAX(DATAPOST) IS NULL THEN DATETIME('1900-01-01') 
ELSE MAX(DATAPOST) END AS DATAMAXIMA, EMAIL 
FROM USUARIO 
LEFT JOIN POST ON POST.EMAIL_USUARIO = USUARIO.EMAIL 
GROUP BY EMAIL) AS POST 
WHERE (USUARIO.EMAIL = POST.EMAIL AND POST.DATAMAXIMA < DATE('now', '-5 years')) AND USUARIO.PAIS= 'brasil');

--16
WITH POSTSSEMANA AS (SELECT POST.CODIGO FROM POST JOIN GRUPO ON POST.CODIGOGRUPO= GRUPO.CODIGO
WHERE CODIGOGRUPO = (SELECT CODIGO FROM GRUPO WHERE NOMEGRUPO = 'IFRS-Campus Rio Grande')
AND POST.CODPOSTREFERENCIA IS NULL
AND POST.DATAPOST BETWEEN DATETIME('NOW', '-7 days') AND DATETIME('NOW', '-1 MINUTE'))
INSERT INTO SELO (EMAIL_USUARIO,
    CODIGOGRUPO,
    DATAINICIO,
    DATAFINAL,
    TIPOSELO)
        SELECT EMAIL, GRUPO.CODIGO, DATE('NOW') AS DATAINICIAL, DATE('NOW', '+7 DAYS', '-1 MINUTE') AS DATAFINAL, 
        CASE WHEN(REACOES.NROREACOES >=  (SELECT COUNT(*) FROM POSTSSEMANA) * 0.75
            AND COMENTARIOS.NROCOMENTARIOS >= (SELECT COUNT(*) FROM POSTSSEMANA) * 0.3) THEN 'Ultra-fã'
        WHEN(REACOES.NROREACOES >=  (SELECT COUNT(*) FROM POSTSSEMANA) * 0.5
        AND COMENTARIOS.NROCOMENTARIOS >= (SELECT COUNT(*) FROM POSTSSEMANA) * 0.2) THEN 'Super-fã'
        WHEN(REACOES.NROREACOES >=  (SELECT COUNT(*) FROM POSTSSEMANA) * 0.25
        AND COMENTARIOS.NROCOMENTARIOS >= (SELECT COUNT(*) FROM POSTSSEMANA) * 0.1) THEN 'Fã'
        ELSE '' END AS  TIPOSELO
        FROM USUARIO JOIN GRUPOUSUARIO ON GRUPOUSUARIO.EMAIL_USUARIO=USUARIO.EMAIL
        JOIN GRUPO ON GRUPOUSUARIO.CODIGOGRUPO = GRUPO.CODIGO
        JOIN 
        (SELECT COUNT(*) AS NROCOMENTARIOS, COMENTARIO.EMAIL_USUARIO FROM POST COMENTARIO 
        JOIN POST POSTAGEM ON COMENTARIO.CODPOSTREFERENCIA = POSTAGEM.CODIGO
        WHERE POSTAGEM.CODIGO IN(SELECT CODIGO FROM POSTSSEMANA)) COMENTARIOS ON COMENTARIOS.EMAIL_USUARIO = USUARIO.EMAIL
        JOIN 
        (SELECT COUNT(*) AS NROREACOES, REACAO.EMAIL_USUARIO FROM REACAO 
        JOIN POST ON REACAO.COD_POST = POST.CODIGO
        WHERE POST.CODIGO IN(SELECT CODIGO FROM POSTSSEMANA)) REACOES ON REACOES.EMAIL_USUARIO = USUARIO.EMAIL
        WHERE GRUPO.NOMEGRUPO='IFRS-Campus Rio Grande';



